version: 1.0.{build}
branches:
  only:
  - MUSHclient
skip_tags: true
skip_branch_with_pr: true
image: Visual Studio 2015
clone_depth: 1
environment:
  auth_token:
    secure: zD0l+yBJscs3IjjlD85Vc1cdXXGWhEXiCrthKrhXe+B8iR03sJW9zAoBJz9md65X
install:
- ps: pushd C:\
- ps: Start-FileDownload 'https://github.com/fiendish/LuaJIT-build/releases/download/latest/lua51.dll'
- ps: Start-FileDownload 'https://github.com/fiendish/lua-llthreads2-build/releases/download/latest/llthreads2.dll'
- ps: Start-FileDownload 'https://github.com/fiendish/lua-openssl-build/releases/download/latest/openssl.dll'
- ps: Start-FileDownload 'https://github.com/nickgammon/mushclient/releases/download/latest_commit/MUSHclient.exe'
- ps: pushd C:\projects\redemptionclientpackage
- ps: |
      Move-Item C:\lua51.dll MUSHclient -force
      Move-Item C:\llthreads2.dll MUSHclient -force
      Move-Item C:\openssl.dll MUSHclient -force
      Move-Item C:\MUSHclient.exe MUSHclient -force
      $env:PACKAGE_VERSION=(Get-Content MUSHclient\RedemptionPackageChanges.txt)[2].split()[0]
      7z a -tzip -mx=9 -mfb=257 Redemption_MUSHclient_$($env:PACKAGE_VERSION)_no_install.zip MUSHclient
      Start-FileDownload 'https://raw.githubusercontent.com/Xinefus-Braska/redemptionclientpackage-installer/master/dbrmush_installer.nsi'
      Start-FileDownload 'https://raw.githubusercontent.com/Xinefus-Braska/redemptionclientpackage-installer/master/get_version.nsi'
      Start-FileDownload 'https://raw.githubusercontent.com/Xinefus-Braska/redemptionclientpackage-installer/master/hello.rtf'
- cmd: '"C:\Program Files (x86)\NSIS\makensis.exe" dbrmush_installer.nsi'
- ps: |
      Get-ChildItem .\Redemption_MUSHclient_r*.exe -Recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
      Get-ChildItem .\Redemption_MUSHclient_r*.zip -Recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
      git checkout -- .
build: off
before_deploy:
- ps: >-
    $env:PACKAGE_VERSION=(Get-Content MUSHclient\RedemptionPackageChanges.txt)[2].split()[0]

    git config --global credential.helper store

    Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:auth_token):x-oauth-basic@github.com`n"

    git config --global user.name "Xinefus-Braska"

    git config --global user.email "hahnhell@gmail.com"

    git remote set-branches --add origin 'gh-pages' 2>&1 | write-host

    git fetch --depth 1 origin gh-pages 2>&1 | write-host

    git checkout gh-pages 2>&1 | write-host

    (Get-Content index.template).replace("%%REV%%", "$env:PACKAGE_VERSION") | Set-Content index.html

    (Get-Content unzip_upgrading.template).replace("%%REV%%", "$env:PACKAGE_VERSION") | Set-Content unzip_upgrading.html

    git add index.html 2>&1 | write-host

    git add unzip_upgrading.html 2>&1 | write-host

    git commit -q -m "automatic rev update $env:PACKAGE_VERSION"

    git push -q origin gh-pages
deploy:
- provider: GitHub
  tag: $(PACKAGE_VERSION)
  auth_token:
    secure: zD0l+yBJscs3IjjlD85Vc1cdXXGWhEXiCrthKrhXe+B8iR03sJW9zAoBJz9md65X
  artifact: /Redemption_MUSHclient_r.*\.(exe|zip)/
  force_update: true
  on:
    branch: MUSHclient
after_deploy:
- cmd:
